### ISSUE TITLE
Erro: UnboundLocalError: local variable 'ponto_final' referenced before assignment

### ISSUE THREAD

**Issue by rodrigobb16** [matheusfillipe/Topografia#5]
Error raised after clicking "Calcular" at "Curvas horizontais" window.

**Comment by matheusfillipe** [comment]
Sorry for the late response and thanks for reaching me out.

Make sure you are running this on qgis > 3.4 and < 3.10, Personally I recommend 3.10. You can find them here: https://download.qgis.org/downloads/, ctrl+F for `3.10`. Other versions weren't tested. I trying to get it working on the latest version of qgis on my free time but qgis updates are coming faster than I.

Anyway, since you got it running I don't think this is a version incompatibility issue so make sure you followed the first steps properly and that you generated a table like in here: https://github.com/matheusfillipe/Topografia/wiki/3.-Tra%C3%A7ado-Horizontal#sobre-o-arquivo-zip-de-projeto.

Also please send the full stack trace of the error that you can see on the `Python Error` tab of the python console: https://github.com/matheusfillipe/Topografia#reportar-erros-ou-bugs

My guess is that the call to `getFeatures` of `gera_vertice` on the layer didn't return anything:
https://github.com/matheusfillipe/Topografia/blob/8eec124a9833b45149afeba69c521488cee051ed/app/model/estacas.py#L784

Could have been an qgis api change this project didn't catch up to. 

Maybe the curve you are trying to create is too small or there aren't enough points so make sure your horizontal draw is big enough and your curve radius is also big like 300m and above. Did you try more times with different plots and that problem always happens? When you change the parameters of the curve does it update? It should be plotting it live while you make changes.

**Comment by robenoliel** [comment]
I'm having trouble reproducing the error, I've been using a different case and now it's not been raised. Although when I click `draw` to view the results it pops up a window saying `Não foi possível definir a geometria. Provavelmente houve a interseção de curvas`, while there's only a single curve. 
I'm also getting an error when running `Gerar todas`, it gives the same pop up window that I just mentioned, until eventually it raises the following Python error:
```
2022-07-04T17:25:03     INFO    ['Traceback (most recent call last):\n', ' File "C:\\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\GeoRoad\\app\\view\\curvas.py", line 448, in drawCurva\n data=circleArc(layer, state, index, self.layer, self.next_index, self.current_index)\n', ' File "C:\\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\GeoRoad\\app\\model\\helper\\qgsgeometry.py", line 298, in circleArc\n l1, l2=getTangentesGeometry(layer2, ic, i)\n', ' File "C:\\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\GeoRoad\\app\\model\\helper\\qgsgeometry.py", line 67, in getTangentesGeometry\n l1=G[i]\n', 'IndexError: list index out of range\n']
```

**Comment by matheusfillipe** [comment]
Does it happen only with circular simples or also with "circular com transição simétrica". It seems to me that there is indeed a bug with "circular simples" but that doesn't happen with the other option. 

![image](https://user-images.githubusercontent.com/24435787/177215069-0fcd9f54-bf5c-4ecf-b4fb-74be39c71258.png)

I started working on making it compatible with newer qgis versions, you could try installing it from this branch: https://github.com/matheusfillipe/Topografia/tree/update-to-qgis-3.24 (click at Code and download zip) And the circular curves might work ok. 

The workflow is clicking first on "Desenhar" (preview the curve part to be added) then "Salvar" (add the curve to the layer) then "Calcular" (update the table).

**Comment by robenoliel** [comment]
Was about to try it, but got a different error opening the estacas file. Are you familiar with it?

```
OSError: [Errno 22] Invalid argument: 'C:\\Users\\RODRIG~1\\AppData\\Local\\Temp\\GeoRoadPluginTemporaryLayers\\georoad_gabao.gpkg-shm' 
Traceback (most recent call last):
  File "C:\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\main.py", line 335, in run_tracado
    self.run = self.estacas.run()
  File "C:\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\controller\estacas.py", line 2091, in run
    finalResult = self.nextView.exec_()
  File "C:\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\view\estacas.py", line 1325, in exec_
    self.openLayers()
  File "C:\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\view\estacas.py", line 1348, in openLayers
    l=self.parent.model.getSavedLayers(self.windowTitle().split(":")[0])
  File "C:\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\model\estacas.py", line 790, in getSavedLayers
    R = [Path(self.saveLayerToPath(str(path.absolute()))) for path in extractZIP(Config.fileName)
  File "C:\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\model\estacas.py", line 790, in 
    R = [Path(self.saveLayerToPath(str(path.absolute()))) for path in extractZIP(Config.fileName)
  File "C:\Users/rodrigobenoliel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\model\estacas.py", line 769, in saveLayerToPath
    return shutil.copy(path, self.tmpFolder())
  File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\RODRIG~1\\AppData\\Local\\Temp\\GeoRoadPluginTemporaryLayers\\georoad_gabao.gpkg-shm'
```
